### ISSUE TITLE
What is the root password?

### ISSUE THREAD

**Issue by chrissound** [Risto-Stevcev/purescript-docker#4]
I'm trying to do a `npm install -g pulp bower` which fails due to not having permission.

And `su` requests a password.

**Comment by Risto-Stevcev** [comment]
Pulp and bower are already installed by the container so you don't have to worry about those

It's based off of the official nodejs container (`node:4`), which creates a `node` user that's mapped the UID 1000:
https://github.com/nodejs/docker-node/blob/master/Dockerfile.template#L3-L4

Docker maps that user to whatever user has that UID on your machine, which in this case isn't the superuser (which has UID 0) but whoever has UID 1000. You can change the user with the `-u` switch

**Comment by chrissound** [comment]
I actually wanted to update them as doing a `pulp build` was giving me warnings, while locally doing `pulp build` did not. 

Thanks for the info!
